[development]
address = "0.0.0.0"
port = 2003
workers = 4
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 2003
workers = 4
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 2003
workers = 10
log = "normal"
limits = { forms = 32768 }
